//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.23 at 12:14:48 PM PDT 
//


package com.google.checkout.sdk.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CheckoutShoppingCart complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CheckoutShoppingCart">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="shopping-cart" type="{http://checkout.google.com/schema/2}ShoppingCart"/>
 *         &lt;element name="checkout-flow-support" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="merchant-checkout-flow-support" type="{http://checkout.google.com/schema/2}MerchantCheckoutFlowSupport"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="order-processing-support" type="{http://checkout.google.com/schema/2}OrderProcessingSupport" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CheckoutShoppingCart", namespace = "http://checkout.google.com/schema/2", propOrder = {

})
public class CheckoutShoppingCart {

    @XmlElement(name = "shopping-cart", namespace = "http://checkout.google.com/schema/2", required = true)
    protected ShoppingCart shoppingCart;
    @XmlElement(name = "checkout-flow-support", namespace = "http://checkout.google.com/schema/2")
    protected CheckoutShoppingCart.CheckoutFlowSupport checkoutFlowSupport;
    @XmlElement(name = "order-processing-support", namespace = "http://checkout.google.com/schema/2")
    protected OrderProcessingSupport orderProcessingSupport;

    /**
     * Gets the value of the shoppingCart property.
     * 
     * @return
     *     possible object is
     *     {@link ShoppingCart }
     *     
     */
    public ShoppingCart getShoppingCart() {
        return shoppingCart;
    }

    /**
     * Sets the value of the shoppingCart property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShoppingCart }
     *     
     */
    public void setShoppingCart(ShoppingCart value) {
        this.shoppingCart = value;
    }

    /**
     * Gets the value of the checkoutFlowSupport property.
     * 
     * @return
     *     possible object is
     *     {@link CheckoutShoppingCart.CheckoutFlowSupport }
     *     
     */
    public CheckoutShoppingCart.CheckoutFlowSupport getCheckoutFlowSupport() {
        return checkoutFlowSupport;
    }

    /**
     * Sets the value of the checkoutFlowSupport property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckoutShoppingCart.CheckoutFlowSupport }
     *     
     */
    public void setCheckoutFlowSupport(CheckoutShoppingCart.CheckoutFlowSupport value) {
        this.checkoutFlowSupport = value;
    }

    /**
     * Gets the value of the orderProcessingSupport property.
     * 
     * @return
     *     possible object is
     *     {@link OrderProcessingSupport }
     *     
     */
    public OrderProcessingSupport getOrderProcessingSupport() {
        return orderProcessingSupport;
    }

    /**
     * Sets the value of the orderProcessingSupport property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderProcessingSupport }
     *     
     */
    public void setOrderProcessingSupport(OrderProcessingSupport value) {
        this.orderProcessingSupport = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="merchant-checkout-flow-support" type="{http://checkout.google.com/schema/2}MerchantCheckoutFlowSupport"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "merchantCheckoutFlowSupport"
    })
    public static class CheckoutFlowSupport {

        @XmlElement(name = "merchant-checkout-flow-support", namespace = "http://checkout.google.com/schema/2")
        protected MerchantCheckoutFlowSupport merchantCheckoutFlowSupport;

        /**
         * Gets the value of the merchantCheckoutFlowSupport property.
         * 
         * @return
         *     possible object is
         *     {@link MerchantCheckoutFlowSupport }
         *     
         */
        public MerchantCheckoutFlowSupport getMerchantCheckoutFlowSupport() {
            return merchantCheckoutFlowSupport;
        }

        /**
         * Sets the value of the merchantCheckoutFlowSupport property.
         * 
         * @param value
         *     allowed object is
         *     {@link MerchantCheckoutFlowSupport }
         *     
         */
        public void setMerchantCheckoutFlowSupport(MerchantCheckoutFlowSupport value) {
            this.merchantCheckoutFlowSupport = value;
        }

    }


    public javax.xml.bind.JAXBElement<CheckoutShoppingCart> toJAXB() {
      return com.google.checkout.sdk.util.Utils.objectFactory().createCheckoutShoppingCart(this);
    }

    @Override
    public String toString() {
      return com.google.checkout.sdk.util.Utils.toXML(toJAXB());
    }
}
