//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.28 at 11:58:56 AM PDT 
//


package com.google.checkout.sdk.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FulfillmentOrderState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FulfillmentOrderState">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="NEW"/>
 *     &lt;enumeration value="PROCESSING"/>
 *     &lt;enumeration value="DELIVERED"/>
 *     &lt;enumeration value="WILL_NOT_DELIVER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FulfillmentOrderState", namespace = "http://checkout.google.com/schema/2")
@XmlEnum
public enum FulfillmentOrderState {

    NEW,
    PROCESSING,
    DELIVERED,
    WILL_NOT_DELIVER;

    public String value() {
        return name();
    }

    public static FulfillmentOrderState fromValue(String v) {
        return valueOf(v);
    }

}
