//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.28 at 11:58:56 AM PDT 
//


package com.google.checkout.sdk.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Item">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="item-weight" type="{http://checkout.google.com/schema/2}ItemWeight" minOccurs="0"/>
 *         &lt;element name="digital-content" type="{http://checkout.google.com/schema/2}DigitalContent" minOccurs="0"/>
 *         &lt;element name="tax-table-selector" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="item-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="item-description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="unit-price" type="{http://checkout.google.com/schema/2}Money"/>
 *         &lt;element name="quantity">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="merchant-item-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="merchant-private-item-data" type="{http://checkout.google.com/schema/2}anyMultiple" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Item", namespace = "http://checkout.google.com/schema/2", propOrder = {

})
public class Item {

    @XmlElement(name = "item-weight", namespace = "http://checkout.google.com/schema/2")
    protected ItemWeight itemWeight;
    @XmlElement(name = "digital-content", namespace = "http://checkout.google.com/schema/2")
    protected DigitalContent digitalContent;
    @XmlElement(name = "tax-table-selector", namespace = "http://checkout.google.com/schema/2")
    protected String taxTableSelector;
    @XmlElement(name = "item-name", namespace = "http://checkout.google.com/schema/2", required = true)
    protected String itemName;
    @XmlElement(name = "item-description", namespace = "http://checkout.google.com/schema/2", required = true)
    protected String itemDescription;
    @XmlElement(name = "unit-price", namespace = "http://checkout.google.com/schema/2", required = true)
    protected Money unitPrice;
    @XmlElement(namespace = "http://checkout.google.com/schema/2")
    protected int quantity;
    @XmlElement(name = "merchant-item-id", namespace = "http://checkout.google.com/schema/2")
    protected String merchantItemId;
    @XmlElement(name = "merchant-private-item-data", namespace = "http://checkout.google.com/schema/2")
    protected AnyMultiple merchantPrivateItemData;

    /**
     * Gets the value of the itemWeight property.
     * 
     * @return
     *     possible object is
     *     {@link ItemWeight }
     *     
     */
    public ItemWeight getItemWeight() {
        return itemWeight;
    }

    /**
     * Sets the value of the itemWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemWeight }
     *     
     */
    public void setItemWeight(ItemWeight value) {
        this.itemWeight = value;
    }

    /**
     * Gets the value of the digitalContent property.
     * 
     * @return
     *     possible object is
     *     {@link DigitalContent }
     *     
     */
    public DigitalContent getDigitalContent() {
        return digitalContent;
    }

    /**
     * Sets the value of the digitalContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigitalContent }
     *     
     */
    public void setDigitalContent(DigitalContent value) {
        this.digitalContent = value;
    }

    /**
     * Gets the value of the taxTableSelector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxTableSelector() {
        return taxTableSelector;
    }

    /**
     * Sets the value of the taxTableSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxTableSelector(String value) {
        this.taxTableSelector = value;
    }

    /**
     * Gets the value of the itemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * Sets the value of the itemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemName(String value) {
        this.itemName = value;
    }

    /**
     * Gets the value of the itemDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemDescription() {
        return itemDescription;
    }

    /**
     * Sets the value of the itemDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemDescription(String value) {
        this.itemDescription = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setUnitPrice(Money value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(int value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the merchantItemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantItemId() {
        return merchantItemId;
    }

    /**
     * Sets the value of the merchantItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantItemId(String value) {
        this.merchantItemId = value;
    }

    /**
     * Gets the value of the merchantPrivateItemData property.
     * 
     * @return
     *     possible object is
     *     {@link AnyMultiple }
     *     
     */
    public AnyMultiple getMerchantPrivateItemData() {
        return merchantPrivateItemData;
    }

    /**
     * Sets the value of the merchantPrivateItemData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyMultiple }
     *     
     */
    public void setMerchantPrivateItemData(AnyMultiple value) {
        this.merchantPrivateItemData = value;
    }

}
