//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.28 at 11:58:56 AM PDT 
//


package com.google.checkout.sdk.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MerchantCheckoutFlowSupport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MerchantCheckoutFlowSupport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="edit-cart-url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="continue-shopping-url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="tax-tables" type="{http://checkout.google.com/schema/2}TaxTables" minOccurs="0"/>
 *         &lt;element name="shipping-methods" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="flat-rate-shipping" type="{http://checkout.google.com/schema/2}FlatRateShipping"/>
 *                     &lt;element name="merchant-calculated-shipping" type="{http://checkout.google.com/schema/2}MerchantCalculatedShipping"/>
 *                     &lt;element name="pickup" type="{http://checkout.google.com/schema/2}Pickup"/>
 *                     &lt;element name="carrier-calculated-shipping" type="{http://checkout.google.com/schema/2}CarrierCalculatedShipping"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="parameterized-urls" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="parameterized-url" type="{http://checkout.google.com/schema/2}ParameterizedUrl" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="merchant-calculations" type="{http://checkout.google.com/schema/2}MerchantCalculations" minOccurs="0"/>
 *         &lt;element name="request-buyer-phone-number" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="analytics-data" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="platform-id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="rounding-policy" type="{http://checkout.google.com/schema/2}RoundingPolicy" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MerchantCheckoutFlowSupport", namespace = "http://checkout.google.com/schema/2", propOrder = {

})
public class MerchantCheckoutFlowSupport {

    @XmlElement(name = "edit-cart-url", namespace = "http://checkout.google.com/schema/2")
    @XmlSchemaType(name = "anyURI")
    protected String editCartUrl;
    @XmlElement(name = "continue-shopping-url", namespace = "http://checkout.google.com/schema/2")
    @XmlSchemaType(name = "anyURI")
    protected String continueShoppingUrl;
    @XmlElement(name = "tax-tables", namespace = "http://checkout.google.com/schema/2")
    protected TaxTables taxTables;
    @XmlElement(name = "shipping-methods", namespace = "http://checkout.google.com/schema/2")
    protected MerchantCheckoutFlowSupport.ShippingMethods shippingMethods;
    @XmlElement(name = "parameterized-urls", namespace = "http://checkout.google.com/schema/2")
    protected MerchantCheckoutFlowSupport.ParameterizedUrls parameterizedUrls;
    @XmlElement(name = "merchant-calculations", namespace = "http://checkout.google.com/schema/2")
    protected MerchantCalculations merchantCalculations;
    @XmlElement(name = "request-buyer-phone-number", namespace = "http://checkout.google.com/schema/2")
    protected Boolean requestBuyerPhoneNumber;
    @XmlElement(name = "analytics-data", namespace = "http://checkout.google.com/schema/2")
    protected String analyticsData;
    @XmlElement(name = "platform-id", namespace = "http://checkout.google.com/schema/2")
    protected Long platformId;
    @XmlElement(name = "rounding-policy", namespace = "http://checkout.google.com/schema/2")
    protected RoundingPolicy roundingPolicy;

    /**
     * Gets the value of the editCartUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditCartUrl() {
        return editCartUrl;
    }

    /**
     * Sets the value of the editCartUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditCartUrl(String value) {
        this.editCartUrl = value;
    }

    /**
     * Gets the value of the continueShoppingUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContinueShoppingUrl() {
        return continueShoppingUrl;
    }

    /**
     * Sets the value of the continueShoppingUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContinueShoppingUrl(String value) {
        this.continueShoppingUrl = value;
    }

    /**
     * Gets the value of the taxTables property.
     * 
     * @return
     *     possible object is
     *     {@link TaxTables }
     *     
     */
    public TaxTables getTaxTables() {
        return taxTables;
    }

    /**
     * Sets the value of the taxTables property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxTables }
     *     
     */
    public void setTaxTables(TaxTables value) {
        this.taxTables = value;
    }

    /**
     * Gets the value of the shippingMethods property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantCheckoutFlowSupport.ShippingMethods }
     *     
     */
    public MerchantCheckoutFlowSupport.ShippingMethods getShippingMethods() {
        return shippingMethods;
    }

    /**
     * Sets the value of the shippingMethods property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantCheckoutFlowSupport.ShippingMethods }
     *     
     */
    public void setShippingMethods(MerchantCheckoutFlowSupport.ShippingMethods value) {
        this.shippingMethods = value;
    }

    /**
     * Gets the value of the parameterizedUrls property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantCheckoutFlowSupport.ParameterizedUrls }
     *     
     */
    public MerchantCheckoutFlowSupport.ParameterizedUrls getParameterizedUrls() {
        return parameterizedUrls;
    }

    /**
     * Sets the value of the parameterizedUrls property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantCheckoutFlowSupport.ParameterizedUrls }
     *     
     */
    public void setParameterizedUrls(MerchantCheckoutFlowSupport.ParameterizedUrls value) {
        this.parameterizedUrls = value;
    }

    /**
     * Gets the value of the merchantCalculations property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantCalculations }
     *     
     */
    public MerchantCalculations getMerchantCalculations() {
        return merchantCalculations;
    }

    /**
     * Sets the value of the merchantCalculations property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantCalculations }
     *     
     */
    public void setMerchantCalculations(MerchantCalculations value) {
        this.merchantCalculations = value;
    }

    /**
     * Gets the value of the requestBuyerPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequestBuyerPhoneNumber() {
        return requestBuyerPhoneNumber;
    }

    /**
     * Sets the value of the requestBuyerPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequestBuyerPhoneNumber(Boolean value) {
        this.requestBuyerPhoneNumber = value;
    }

    /**
     * Gets the value of the analyticsData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnalyticsData() {
        return analyticsData;
    }

    /**
     * Sets the value of the analyticsData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnalyticsData(String value) {
        this.analyticsData = value;
    }

    /**
     * Gets the value of the platformId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPlatformId() {
        return platformId;
    }

    /**
     * Sets the value of the platformId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPlatformId(Long value) {
        this.platformId = value;
    }

    /**
     * Gets the value of the roundingPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link RoundingPolicy }
     *     
     */
    public RoundingPolicy getRoundingPolicy() {
        return roundingPolicy;
    }

    /**
     * Sets the value of the roundingPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoundingPolicy }
     *     
     */
    public void setRoundingPolicy(RoundingPolicy value) {
        this.roundingPolicy = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="parameterized-url" type="{http://checkout.google.com/schema/2}ParameterizedUrl" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parameterizedUrl"
    })
    public static class ParameterizedUrls {

        @XmlElement(name = "parameterized-url", namespace = "http://checkout.google.com/schema/2")
        protected List<ParameterizedUrl> parameterizedUrl;

        /**
         * Gets the value of the parameterizedUrl property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parameterizedUrl property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParameterizedUrl().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ParameterizedUrl }
         * 
         * 
         */
        public List<ParameterizedUrl> getParameterizedUrl() {
            if (parameterizedUrl == null) {
                parameterizedUrl = new ArrayList<ParameterizedUrl>();
            }
            return this.parameterizedUrl;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="flat-rate-shipping" type="{http://checkout.google.com/schema/2}FlatRateShipping"/>
     *           &lt;element name="merchant-calculated-shipping" type="{http://checkout.google.com/schema/2}MerchantCalculatedShipping"/>
     *           &lt;element name="pickup" type="{http://checkout.google.com/schema/2}Pickup"/>
     *           &lt;element name="carrier-calculated-shipping" type="{http://checkout.google.com/schema/2}CarrierCalculatedShipping"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "flatRateShippingOrMerchantCalculatedShippingOrPickup"
    })
    public static class ShippingMethods {

        @XmlElements({
            @XmlElement(name = "carrier-calculated-shipping", namespace = "http://checkout.google.com/schema/2", type = CarrierCalculatedShipping.class),
            @XmlElement(name = "merchant-calculated-shipping", namespace = "http://checkout.google.com/schema/2", type = MerchantCalculatedShipping.class),
            @XmlElement(name = "flat-rate-shipping", namespace = "http://checkout.google.com/schema/2", type = FlatRateShipping.class),
            @XmlElement(name = "pickup", namespace = "http://checkout.google.com/schema/2", type = Pickup.class)
        })
        protected List<Object> flatRateShippingOrMerchantCalculatedShippingOrPickup;

        /**
         * Gets the value of the flatRateShippingOrMerchantCalculatedShippingOrPickup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the flatRateShippingOrMerchantCalculatedShippingOrPickup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFlatRateShippingOrMerchantCalculatedShippingOrPickup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CarrierCalculatedShipping }
         * {@link MerchantCalculatedShipping }
         * {@link FlatRateShipping }
         * {@link Pickup }
         * 
         * 
         */
        public List<Object> getFlatRateShippingOrMerchantCalculatedShippingOrPickup() {
            if (flatRateShippingOrMerchantCalculatedShippingOrPickup == null) {
                flatRateShippingOrMerchantCalculatedShippingOrPickup = new ArrayList<Object>();
            }
            return this.flatRateShippingOrMerchantCalculatedShippingOrPickup;
        }

    }

}
