//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.23 at 12:14:48 PM PDT 
//


package com.google.checkout.sdk.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.google.checkout.sdk.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ArchiveOrder_QNAME = new QName("http://checkout.google.com/schema/2", "archive-order");
    private final static QName _AddTrackingData_QNAME = new QName("http://checkout.google.com/schema/2", "add-tracking-data");
    private final static QName _Diagnosis_QNAME = new QName("http://checkout.google.com/schema/2", "diagnosis");
    private final static QName _ChargebackAmountNotification_QNAME = new QName("http://checkout.google.com/schema/2", "chargeback-amount-notification");
    private final static QName _OrderSummaryRequest_QNAME = new QName("http://checkout.google.com/schema/2", "order-summary-request");
    private final static QName _OrderSummaryResponse_QNAME = new QName("http://checkout.google.com/schema/2", "order-summary-response");
    private final static QName _CheckoutShoppingCart_QNAME = new QName("http://checkout.google.com/schema/2", "checkout-shopping-cart");
    private final static QName _OrderStateChangeNotification_QNAME = new QName("http://checkout.google.com/schema/2", "order-state-change-notification");
    private final static QName _ChargeAndShipOrder_QNAME = new QName("http://checkout.google.com/schema/2", "charge-and-ship-order");
    private final static QName _BuyerMarketingPreferences_QNAME = new QName("http://checkout.google.com/schema/2", "buyer-marketing-preferences");
    private final static QName _CheckoutRedirect_QNAME = new QName("http://checkout.google.com/schema/2", "checkout-redirect");
    private final static QName _RiskInformationNotification_QNAME = new QName("http://checkout.google.com/schema/2", "risk-information-notification");
    private final static QName _CancelItems_QNAME = new QName("http://checkout.google.com/schema/2", "cancel-items");
    private final static QName _BackorderItems_QNAME = new QName("http://checkout.google.com/schema/2", "backorder-items");
    private final static QName _ProcessOrder_QNAME = new QName("http://checkout.google.com/schema/2", "process-order");
    private final static QName _UnarchiveOrder_QNAME = new QName("http://checkout.google.com/schema/2", "unarchive-order");
    private final static QName _ReturnItems_QNAME = new QName("http://checkout.google.com/schema/2", "return-items");
    private final static QName _MerchantCalculationCallback_QNAME = new QName("http://checkout.google.com/schema/2", "merchant-calculation-callback");
    private final static QName _ChargeOrder_QNAME = new QName("http://checkout.google.com/schema/2", "charge-order");
    private final static QName _Bye_QNAME = new QName("http://checkout.google.com/schema/2", "bye");
    private final static QName _CancelOrder_QNAME = new QName("http://checkout.google.com/schema/2", "cancel-order");
    private final static QName _ChargeAmountNotification_QNAME = new QName("http://checkout.google.com/schema/2", "charge-amount-notification");
    private final static QName _RefundOrder_QNAME = new QName("http://checkout.google.com/schema/2", "refund-order");
    private final static QName _MerchantCalculationResults_QNAME = new QName("http://checkout.google.com/schema/2", "merchant-calculation-results");
    private final static QName _NewOrderNotification_QNAME = new QName("http://checkout.google.com/schema/2", "new-order-notification");
    private final static QName _Error_QNAME = new QName("http://checkout.google.com/schema/2", "error");
    private final static QName _ResetItemsShippingInformation_QNAME = new QName("http://checkout.google.com/schema/2", "reset-items-shipping-information");
    private final static QName _SendBuyerMessage_QNAME = new QName("http://checkout.google.com/schema/2", "send-buyer-message");
    private final static QName _AuthorizeOrder_QNAME = new QName("http://checkout.google.com/schema/2", "authorize-order");
    private final static QName _NotificationAcknowledgment_QNAME = new QName("http://checkout.google.com/schema/2", "notification-acknowledgment");
    private final static QName _AuthorizationAmountNotification_QNAME = new QName("http://checkout.google.com/schema/2", "authorization-amount-notification");
    private final static QName _OrderSummary_QNAME = new QName("http://checkout.google.com/schema/2", "order-summary");
    private final static QName _ShipItems_QNAME = new QName("http://checkout.google.com/schema/2", "ship-items");
    private final static QName _NotificationHistoryResponse_QNAME = new QName("http://checkout.google.com/schema/2", "notification-history-response");
    private final static QName _RefundAmountNotification_QNAME = new QName("http://checkout.google.com/schema/2", "refund-amount-notification");
    private final static QName _Hello_QNAME = new QName("http://checkout.google.com/schema/2", "hello");
    private final static QName _NotificationHistoryRequest_QNAME = new QName("http://checkout.google.com/schema/2", "notification-history-request");
    private final static QName _OrderListRequest_QNAME = new QName("http://checkout.google.com/schema/2", "order-list-request");
    private final static QName _DeliverOrder_QNAME = new QName("http://checkout.google.com/schema/2", "deliver-order");
    private final static QName _AddMerchantOrderNumber_QNAME = new QName("http://checkout.google.com/schema/2", "add-merchant-order-number");
    private final static QName _DemoFailure_QNAME = new QName("http://checkout.google.com/schema/2", "demo-failure");
    private final static QName _RequestReceived_QNAME = new QName("http://checkout.google.com/schema/2", "request-received");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.google.checkout.sdk.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AnonymousAddress }
     * 
     */
    public AnonymousAddress createAnonymousAddress() {
        return new AnonymousAddress();
    }

    /**
     * Create an instance of {@link GiftAidOptions }
     * 
     */
    public GiftAidOptions createGiftAidOptions() {
        return new GiftAidOptions();
    }

    /**
     * Create an instance of {@link GiftCertificateAdjustment }
     * 
     */
    public GiftCertificateAdjustment createGiftCertificateAdjustment() {
        return new GiftCertificateAdjustment();
    }

    /**
     * Create an instance of {@link AlternateTaxRule }
     * 
     */
    public AlternateTaxRule createAlternateTaxRule() {
        return new AlternateTaxRule();
    }

    /**
     * Create an instance of {@link FlatRateShipping }
     * 
     */
    public FlatRateShipping createFlatRateShipping() {
        return new FlatRateShipping();
    }

    /**
     * Create an instance of {@link USStateArea }
     * 
     */
    public USStateArea createUSStateArea() {
        return new USStateArea();
    }

    /**
     * Create an instance of {@link ChargebackAmountNotification }
     * 
     */
    public ChargebackAmountNotification createChargebackAmountNotification() {
        return new ChargebackAmountNotification();
    }

    /**
     * Create an instance of {@link BuyerMarketingPreferences }
     * 
     */
    public BuyerMarketingPreferences createBuyerMarketingPreferences() {
        return new BuyerMarketingPreferences();
    }

    /**
     * Create an instance of {@link ShippingRestrictions }
     * 
     */
    public ShippingRestrictions createShippingRestrictions() {
        return new ShippingRestrictions();
    }

    /**
     * Create an instance of {@link Calculate }
     * 
     */
    public Calculate createCalculate() {
        return new Calculate();
    }

    /**
     * Create an instance of {@link Result.MerchantCodeResults }
     * 
     */
    public Result.MerchantCodeResults createResultMerchantCodeResults() {
        return new Result.MerchantCodeResults();
    }

    /**
     * Create an instance of {@link OrderAdjustment.MerchantCodes }
     * 
     */
    public OrderAdjustment.MerchantCodes createOrderAdjustmentMerchantCodes() {
        return new OrderAdjustment.MerchantCodes();
    }

    /**
     * Create an instance of {@link ParameterizedUrl.Parameters }
     * 
     */
    public ParameterizedUrl.Parameters createParameterizedUrlParameters() {
        return new ParameterizedUrl.Parameters();
    }

    /**
     * Create an instance of {@link ChargeAndShipOrderRequest.ItemShippingInformationList }
     * 
     */
    public ChargeAndShipOrderRequest.ItemShippingInformationList createChargeAndShipOrderRequestItemShippingInformationList() {
        return new ChargeAndShipOrderRequest.ItemShippingInformationList();
    }

    /**
     * Create an instance of {@link USCountryArea }
     * 
     */
    public USCountryArea createUSCountryArea() {
        return new USCountryArea();
    }

    /**
     * Create an instance of {@link ItemId }
     * 
     */
    public ItemId createItemId() {
        return new ItemId();
    }

    /**
     * Create an instance of {@link MerchantCalculatedShipping.Price }
     * 
     */
    public MerchantCalculatedShipping.Price createMerchantCalculatedShippingPrice() {
        return new MerchantCalculatedShipping.Price();
    }

    /**
     * Create an instance of {@link DiagnoseResponse }
     * 
     */
    public DiagnoseResponse createDiagnoseResponse() {
        return new DiagnoseResponse();
    }

    /**
     * Create an instance of {@link AlternateTaxRule.TaxAreas }
     * 
     */
    public AlternateTaxRule.TaxAreas createAlternateTaxRuleTaxAreas() {
        return new AlternateTaxRule.TaxAreas();
    }

    /**
     * Create an instance of {@link MerchantCheckoutFlowSupport }
     * 
     */
    public MerchantCheckoutFlowSupport createMerchantCheckoutFlowSupport() {
        return new MerchantCheckoutFlowSupport();
    }

    /**
     * Create an instance of {@link ShippingRestrictions.AllowedAreas }
     * 
     */
    public ShippingRestrictions.AllowedAreas createShippingRestrictionsAllowedAreas() {
        return new ShippingRestrictions.AllowedAreas();
    }

    /**
     * Create an instance of {@link AddTrackingDataRequest }
     * 
     */
    public AddTrackingDataRequest createAddTrackingDataRequest() {
        return new AddTrackingDataRequest();
    }

    /**
     * Create an instance of {@link CheckoutShoppingCart }
     * 
     */
    public CheckoutShoppingCart createCheckoutShoppingCart() {
        return new CheckoutShoppingCart();
    }

    /**
     * Create an instance of {@link ResetItemsShippingInformationRequest.ItemIds }
     * 
     */
    public ResetItemsShippingInformationRequest.ItemIds createResetItemsShippingInformationRequestItemIds() {
        return new ResetItemsShippingInformationRequest.ItemIds();
    }

    /**
     * Create an instance of {@link NotificationHistoryResponse }
     * 
     */
    public NotificationHistoryResponse createNotificationHistoryResponse() {
        return new NotificationHistoryResponse();
    }

    /**
     * Create an instance of {@link Result.ShippingRate }
     * 
     */
    public Result.ShippingRate createResultShippingRate() {
        return new Result.ShippingRate();
    }

    /**
     * Create an instance of {@link OrderAdjustment.Shipping }
     * 
     */
    public OrderAdjustment.Shipping createOrderAdjustmentShipping() {
        return new OrderAdjustment.Shipping();
    }

    /**
     * Create an instance of {@link EmploymentInformation }
     * 
     */
    public EmploymentInformation createEmploymentInformation() {
        return new EmploymentInformation();
    }

    /**
     * Create an instance of {@link TaxTables.AlternateTaxTables }
     * 
     */
    public TaxTables.AlternateTaxTables createTaxTablesAlternateTaxTables() {
        return new TaxTables.AlternateTaxTables();
    }

    /**
     * Create an instance of {@link NotificationHistoryRequest.NotificationTypes }
     * 
     */
    public NotificationHistoryRequest.NotificationTypes createNotificationHistoryRequestNotificationTypes() {
        return new NotificationHistoryRequest.NotificationTypes();
    }

    /**
     * Create an instance of {@link DeliveryInstructions }
     * 
     */
    public DeliveryInstructions createDeliveryInstructions() {
        return new DeliveryInstructions();
    }

    /**
     * Create an instance of {@link CancelOrderRequest }
     * 
     */
    public CancelOrderRequest createCancelOrderRequest() {
        return new CancelOrderRequest();
    }

    /**
     * Create an instance of {@link SendBuyerMessageRequest }
     * 
     */
    public SendBuyerMessageRequest createSendBuyerMessageRequest() {
        return new SendBuyerMessageRequest();
    }

    /**
     * Create an instance of {@link USZipArea }
     * 
     */
    public USZipArea createUSZipArea() {
        return new USZipArea();
    }

    /**
     * Create an instance of {@link AnyType }
     * 
     */
    public AnyType createAnyType() {
        return new AnyType();
    }

    /**
     * Create an instance of {@link Promotion }
     * 
     */
    public Promotion createPromotion() {
        return new Promotion();
    }

    /**
     * Create an instance of {@link CancelItemsRequest.ItemIds }
     * 
     */
    public CancelItemsRequest.ItemIds createCancelItemsRequestItemIds() {
        return new CancelItemsRequest.ItemIds();
    }

    /**
     * Create an instance of {@link DemoFailure }
     * 
     */
    public DemoFailure createDemoFailure() {
        return new DemoFailure();
    }

    /**
     * Create an instance of {@link ShipItemsRequest.ItemShippingInformationList }
     * 
     */
    public ShipItemsRequest.ItemShippingInformationList createShipItemsRequestItemShippingInformationList() {
        return new ShipItemsRequest.ItemShippingInformationList();
    }

    /**
     * Create an instance of {@link RefundOrderRequest }
     * 
     */
    public RefundOrderRequest createRefundOrderRequest() {
        return new RefundOrderRequest();
    }

    /**
     * Create an instance of {@link RoundingPolicy }
     * 
     */
    public RoundingPolicy createRoundingPolicy() {
        return new RoundingPolicy();
    }

    /**
     * Create an instance of {@link GiftCertificateResult }
     * 
     */
    public GiftCertificateResult createGiftCertificateResult() {
        return new GiftCertificateResult();
    }

    /**
     * Create an instance of {@link OrderSummaryResponse.OrderSummaries }
     * 
     */
    public OrderSummaryResponse.OrderSummaries createOrderSummaryResponseOrderSummaries() {
        return new OrderSummaryResponse.OrderSummaries();
    }

    /**
     * Create an instance of {@link DefaultTaxRule }
     * 
     */
    public DefaultTaxRule createDefaultTaxRule() {
        return new DefaultTaxRule();
    }

    /**
     * Create an instance of {@link RiskInformation }
     * 
     */
    public RiskInformation createRiskInformation() {
        return new RiskInformation();
    }

    /**
     * Create an instance of {@link CouponAdjustment.CalculatedAmount }
     * 
     */
    public CouponAdjustment.CalculatedAmount createCouponAdjustmentCalculatedAmount() {
        return new CouponAdjustment.CalculatedAmount();
    }

    /**
     * Create an instance of {@link MerchantCodeString }
     * 
     */
    public MerchantCodeString createMerchantCodeString() {
        return new MerchantCodeString();
    }

    /**
     * Create an instance of {@link GiftCertificateResult.CalculatedAmount }
     * 
     */
    public GiftCertificateResult.CalculatedAmount createGiftCertificateResultCalculatedAmount() {
        return new GiftCertificateResult.CalculatedAmount();
    }

    /**
     * Create an instance of {@link ErrorResponse }
     * 
     */
    public ErrorResponse createErrorResponse() {
        return new ErrorResponse();
    }

    /**
     * Create an instance of {@link GiftCertificateAdjustment.AppliedAmount }
     * 
     */
    public GiftCertificateAdjustment.AppliedAmount createGiftCertificateAdjustmentAppliedAmount() {
        return new GiftCertificateAdjustment.AppliedAmount();
    }

    /**
     * Create an instance of {@link InHonorOfMessage }
     * 
     */
    public InHonorOfMessage createInHonorOfMessage() {
        return new InHonorOfMessage();
    }

    /**
     * Create an instance of {@link ReturnItemsRequest }
     * 
     */
    public ReturnItemsRequest createReturnItemsRequest() {
        return new ReturnItemsRequest();
    }

    /**
     * Create an instance of {@link RefundAmountNotification }
     * 
     */
    public RefundAmountNotification createRefundAmountNotification() {
        return new RefundAmountNotification();
    }

    /**
     * Create an instance of {@link Result.TotalTax }
     * 
     */
    public Result.TotalTax createResultTotalTax() {
        return new Result.TotalTax();
    }

    /**
     * Create an instance of {@link NewOrderNotification.Promotions }
     * 
     */
    public NewOrderNotification.Promotions createNewOrderNotificationPromotions() {
        return new NewOrderNotification.Promotions();
    }

    /**
     * Create an instance of {@link CarrierCalculatedShipping.ShippingPackages }
     * 
     */
    public CarrierCalculatedShipping.ShippingPackages createCarrierCalculatedShippingShippingPackages() {
        return new CarrierCalculatedShipping.ShippingPackages();
    }

    /**
     * Create an instance of {@link OrderAdjustment.TotalTax }
     * 
     */
    public OrderAdjustment.TotalTax createOrderAdjustmentTotalTax() {
        return new OrderAdjustment.TotalTax();
    }

    /**
     * Create an instance of {@link PickupShippingAdjustment }
     * 
     */
    public PickupShippingAdjustment createPickupShippingAdjustment() {
        return new PickupShippingAdjustment();
    }

    /**
     * Create an instance of {@link OrderListRequest }
     * 
     */
    public OrderListRequest createOrderListRequest() {
        return new OrderListRequest();
    }

    /**
     * Create an instance of {@link Method }
     * 
     */
    public Method createMethod() {
        return new Method();
    }

    /**
     * Create an instance of {@link NotificationHistoryRequest }
     * 
     */
    public NotificationHistoryRequest createNotificationHistoryRequest() {
        return new NotificationHistoryRequest();
    }

    /**
     * Create an instance of {@link ShippingPackage }
     * 
     */
    public ShippingPackage createShippingPackage() {
        return new ShippingPackage();
    }

    /**
     * Create an instance of {@link TrackingData }
     * 
     */
    public TrackingData createTrackingData() {
        return new TrackingData();
    }

    /**
     * Create an instance of {@link InMemoryOfMessage }
     * 
     */
    public InMemoryOfMessage createInMemoryOfMessage() {
        return new InMemoryOfMessage();
    }

    /**
     * Create an instance of {@link AlternateTaxTable }
     * 
     */
    public AlternateTaxTable createAlternateTaxTable() {
        return new AlternateTaxTable();
    }

    /**
     * Create an instance of {@link ShippingRestrictions.ExcludedAreas }
     * 
     */
    public ShippingRestrictions.ExcludedAreas createShippingRestrictionsExcludedAreas() {
        return new ShippingRestrictions.ExcludedAreas();
    }

    /**
     * Create an instance of {@link ParameterizedUrl }
     * 
     */
    public ParameterizedUrl createParameterizedUrl() {
        return new ParameterizedUrl();
    }

    /**
     * Create an instance of {@link AnyMultiple }
     * 
     */
    public AnyMultiple createAnyMultiple() {
        return new AnyMultiple();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link ChargeAndShipOrderRequest }
     * 
     */
    public ChargeAndShipOrderRequest createChargeAndShipOrderRequest() {
        return new ChargeAndShipOrderRequest();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link SpecialRequests }
     * 
     */
    public SpecialRequests createSpecialRequests() {
        return new SpecialRequests();
    }

    /**
     * Create an instance of {@link ChargeAndShipOrderRequest.TrackingDataList }
     * 
     */
    public ChargeAndShipOrderRequest.TrackingDataList createChargeAndShipOrderRequestTrackingDataList() {
        return new ChargeAndShipOrderRequest.TrackingDataList();
    }

    /**
     * Create an instance of {@link CouponAdjustment }
     * 
     */
    public CouponAdjustment createCouponAdjustment() {
        return new CouponAdjustment();
    }

    /**
     * Create an instance of {@link DefaultTaxTable.TaxRules }
     * 
     */
    public DefaultTaxTable.TaxRules createDefaultTaxTableTaxRules() {
        return new DefaultTaxTable.TaxRules();
    }

    /**
     * Create an instance of {@link AlternateTaxTable.AlternateTaxRules }
     * 
     */
    public AlternateTaxTable.AlternateTaxRules createAlternateTaxTableAlternateTaxRules() {
        return new AlternateTaxTable.AlternateTaxRules();
    }

    /**
     * Create an instance of {@link ItemShippingInformation }
     * 
     */
    public ItemShippingInformation createItemShippingInformation() {
        return new ItemShippingInformation();
    }

    /**
     * Create an instance of {@link Calculate.MerchantCodeStrings }
     * 
     */
    public Calculate.MerchantCodeStrings createCalculateMerchantCodeStrings() {
        return new Calculate.MerchantCodeStrings();
    }

    /**
     * Create an instance of {@link MerchantCheckoutFlowSupport.ParameterizedUrls }
     * 
     */
    public MerchantCheckoutFlowSupport.ParameterizedUrls createMerchantCheckoutFlowSupportParameterizedUrls() {
        return new MerchantCheckoutFlowSupport.ParameterizedUrls();
    }

    /**
     * Create an instance of {@link MerchantCalculatedShippingAdjustment.ShippingCost }
     * 
     */
    public MerchantCalculatedShippingAdjustment.ShippingCost createMerchantCalculatedShippingAdjustmentShippingCost() {
        return new MerchantCalculatedShippingAdjustment.ShippingCost();
    }

    /**
     * Create an instance of {@link MerchantCalculationCallback }
     * 
     */
    public MerchantCalculationCallback createMerchantCalculationCallback() {
        return new MerchantCalculationCallback();
    }

    /**
     * Create an instance of {@link ShoppingCart.BuyerMessages }
     * 
     */
    public ShoppingCart.BuyerMessages createShoppingCartBuyerMessages() {
        return new ShoppingCart.BuyerMessages();
    }

    /**
     * Create an instance of {@link OrderSummaryResponse }
     * 
     */
    public OrderSummaryResponse createOrderSummaryResponse() {
        return new OrderSummaryResponse();
    }

    /**
     * Create an instance of {@link CarrierCalculatedShippingAdjustment.ShippingCost }
     * 
     */
    public CarrierCalculatedShippingAdjustment.ShippingCost createCarrierCalculatedShippingAdjustmentShippingCost() {
        return new CarrierCalculatedShippingAdjustment.ShippingCost();
    }

    /**
     * Create an instance of {@link ErrorResponse.WarningMessages }
     * 
     */
    public ErrorResponse.WarningMessages createErrorResponseWarningMessages() {
        return new ErrorResponse.WarningMessages();
    }

    /**
     * Create an instance of {@link Calculate.Addresses }
     * 
     */
    public Calculate.Addresses createCalculateAddresses() {
        return new Calculate.Addresses();
    }

    /**
     * Create an instance of {@link ItemShippingInformation.TrackingDataList }
     * 
     */
    public ItemShippingInformation.TrackingDataList createItemShippingInformationTrackingDataList() {
        return new ItemShippingInformation.TrackingDataList();
    }

    /**
     * Create an instance of {@link CouponResult.CalculatedAmount }
     * 
     */
    public CouponResult.CalculatedAmount createCouponResultCalculatedAmount() {
        return new CouponResult.CalculatedAmount();
    }

    /**
     * Create an instance of {@link DigitalContent }
     * 
     */
    public DigitalContent createDigitalContent() {
        return new DigitalContent();
    }

    /**
     * Create an instance of {@link DeliverOrderRequest }
     * 
     */
    public DeliverOrderRequest createDeliverOrderRequest() {
        return new DeliverOrderRequest();
    }

    /**
     * Create an instance of {@link OrderSummary.Promotions }
     * 
     */
    public OrderSummary.Promotions createOrderSummaryPromotions() {
        return new OrderSummary.Promotions();
    }

    /**
     * Create an instance of {@link CarrierCalculatedShipping.CarrierCalculatedShippingOptions }
     * 
     */
    public CarrierCalculatedShipping.CarrierCalculatedShippingOptions createCarrierCalculatedShippingCarrierCalculatedShippingOptions() {
        return new CarrierCalculatedShipping.CarrierCalculatedShippingOptions();
    }

    /**
     * Create an instance of {@link CheckoutShoppingCart.CheckoutFlowSupport }
     * 
     */
    public CheckoutShoppingCart.CheckoutFlowSupport createCheckoutShoppingCartCheckoutFlowSupport() {
        return new CheckoutShoppingCart.CheckoutFlowSupport();
    }

    /**
     * Create an instance of {@link SpecialInstructions }
     * 
     */
    public SpecialInstructions createSpecialInstructions() {
        return new SpecialInstructions();
    }

    /**
     * Create an instance of {@link InTributeOfMessage }
     * 
     */
    public InTributeOfMessage createInTributeOfMessage() {
        return new InTributeOfMessage();
    }

    /**
     * Create an instance of {@link OrderSummaryRequest }
     * 
     */
    public OrderSummaryRequest createOrderSummaryRequest() {
        return new OrderSummaryRequest();
    }

    /**
     * Create an instance of {@link NewOrderNotification }
     * 
     */
    public NewOrderNotification createNewOrderNotification() {
        return new NewOrderNotification();
    }

    /**
     * Create an instance of {@link FlatRateShippingAdjustment }
     * 
     */
    public FlatRateShippingAdjustment createFlatRateShippingAdjustment() {
        return new FlatRateShippingAdjustment();
    }

    /**
     * Create an instance of {@link OrderProcessingSupport }
     * 
     */
    public OrderProcessingSupport createOrderProcessingSupport() {
        return new OrderProcessingSupport();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link FlatRateShipping.Price }
     * 
     */
    public FlatRateShipping.Price createFlatRateShippingPrice() {
        return new FlatRateShipping.Price();
    }

    /**
     * Create an instance of {@link UnarchiveOrderRequest }
     * 
     */
    public UnarchiveOrderRequest createUnarchiveOrderRequest() {
        return new UnarchiveOrderRequest();
    }

    /**
     * Create an instance of {@link ShoppingCart }
     * 
     */
    public ShoppingCart createShoppingCart() {
        return new ShoppingCart();
    }

    /**
     * Create an instance of {@link CheckoutRedirect }
     * 
     */
    public CheckoutRedirect createCheckoutRedirect() {
        return new CheckoutRedirect();
    }

    /**
     * Create an instance of {@link DefaultTaxRule.TaxArea }
     * 
     */
    public DefaultTaxRule.TaxArea createDefaultTaxRuleTaxArea() {
        return new DefaultTaxRule.TaxArea();
    }

    /**
     * Create an instance of {@link RiskInformationNotification }
     * 
     */
    public RiskInformationNotification createRiskInformationNotification() {
        return new RiskInformationNotification();
    }

    /**
     * Create an instance of {@link TaxTables }
     * 
     */
    public TaxTables createTaxTables() {
        return new TaxTables();
    }

    /**
     * Create an instance of {@link CouponAdjustment.AppliedAmount }
     * 
     */
    public CouponAdjustment.AppliedAmount createCouponAdjustmentAppliedAmount() {
        return new CouponAdjustment.AppliedAmount();
    }

    /**
     * Create an instance of {@link BackorderItemsRequest.ItemIds }
     * 
     */
    public BackorderItemsRequest.ItemIds createBackorderItemsRequestItemIds() {
        return new BackorderItemsRequest.ItemIds();
    }

    /**
     * Create an instance of {@link MerchantCalculatedShipping }
     * 
     */
    public MerchantCalculatedShipping createMerchantCalculatedShipping() {
        return new MerchantCalculatedShipping();
    }

    /**
     * Create an instance of {@link NotificationAcknowledgment }
     * 
     */
    public NotificationAcknowledgment createNotificationAcknowledgment() {
        return new NotificationAcknowledgment();
    }

    /**
     * Create an instance of {@link NotificationHistoryResponse.Notifications }
     * 
     */
    public NotificationHistoryResponse.Notifications createNotificationHistoryResponseNotifications() {
        return new NotificationHistoryResponse.Notifications();
    }

    /**
     * Create an instance of {@link AlternateTaxRule.TaxArea }
     * 
     */
    public AlternateTaxRule.TaxArea createAlternateTaxRuleTaxArea() {
        return new AlternateTaxRule.TaxArea();
    }

    /**
     * Create an instance of {@link RequestReceivedResponse }
     * 
     */
    public RequestReceivedResponse createRequestReceivedResponse() {
        return new RequestReceivedResponse();
    }

    /**
     * Create an instance of {@link FlatRateShippingAdjustment.ShippingCost }
     * 
     */
    public FlatRateShippingAdjustment.ShippingCost createFlatRateShippingAdjustmentShippingCost() {
        return new FlatRateShippingAdjustment.ShippingCost();
    }

    /**
     * Create an instance of {@link Pickup.Price }
     * 
     */
    public Pickup.Price createPickupPrice() {
        return new Pickup.Price();
    }

    /**
     * Create an instance of {@link OrderSummary }
     * 
     */
    public OrderSummary createOrderSummary() {
        return new OrderSummary();
    }

    /**
     * Create an instance of {@link ItemWeight }
     * 
     */
    public ItemWeight createItemWeight() {
        return new ItemWeight();
    }

    /**
     * Create an instance of {@link OrderAdjustment }
     * 
     */
    public OrderAdjustment createOrderAdjustment() {
        return new OrderAdjustment();
    }

    /**
     * Create an instance of {@link PostalArea }
     * 
     */
    public PostalArea createPostalArea() {
        return new PostalArea();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link ArchiveOrderRequest }
     * 
     */
    public ArchiveOrderRequest createArchiveOrderRequest() {
        return new ArchiveOrderRequest();
    }

    /**
     * Create an instance of {@link AuthorizationInformation }
     * 
     */
    public AuthorizationInformation createAuthorizationInformation() {
        return new AuthorizationInformation();
    }

    /**
     * Create an instance of {@link MerchantCheckoutFlowSupport.ShippingMethods }
     * 
     */
    public MerchantCheckoutFlowSupport.ShippingMethods createMerchantCheckoutFlowSupportShippingMethods() {
        return new MerchantCheckoutFlowSupport.ShippingMethods();
    }

    /**
     * Create an instance of {@link EUArea }
     * 
     */
    public EUArea createEUArea() {
        return new EUArea();
    }

    /**
     * Create an instance of {@link ChargeOrderRequest }
     * 
     */
    public ChargeOrderRequest createChargeOrderRequest() {
        return new ChargeOrderRequest();
    }

    /**
     * Create an instance of {@link UrlParameter }
     * 
     */
    public UrlParameter createUrlParameter() {
        return new UrlParameter();
    }

    /**
     * Create an instance of {@link OrderSummaryRequest.OrderNumbers }
     * 
     */
    public OrderSummaryRequest.OrderNumbers createOrderSummaryRequestOrderNumbers() {
        return new OrderSummaryRequest.OrderNumbers();
    }

    /**
     * Create an instance of {@link ProcessOrderRequest }
     * 
     */
    public ProcessOrderRequest createProcessOrderRequest() {
        return new ProcessOrderRequest();
    }

    /**
     * Create an instance of {@link GiftCertificateAdjustment.CalculatedAmount }
     * 
     */
    public GiftCertificateAdjustment.CalculatedAmount createGiftCertificateAdjustmentCalculatedAmount() {
        return new GiftCertificateAdjustment.CalculatedAmount();
    }

    /**
     * Create an instance of {@link MerchantCalculations }
     * 
     */
    public MerchantCalculations createMerchantCalculations() {
        return new MerchantCalculations();
    }

    /**
     * Create an instance of {@link FeeStructure }
     * 
     */
    public FeeStructure createFeeStructure() {
        return new FeeStructure();
    }

    /**
     * Create an instance of {@link ChargeAmountNotification }
     * 
     */
    public ChargeAmountNotification createChargeAmountNotification() {
        return new ChargeAmountNotification();
    }

    /**
     * Create an instance of {@link NotificationHistoryRequest.OrderNumbers }
     * 
     */
    public NotificationHistoryRequest.OrderNumbers createNotificationHistoryRequestOrderNumbers() {
        return new NotificationHistoryRequest.OrderNumbers();
    }

    /**
     * Create an instance of {@link Hello }
     * 
     */
    public Hello createHello() {
        return new Hello();
    }

    /**
     * Create an instance of {@link AddMerchantOrderNumberRequest }
     * 
     */
    public AddMerchantOrderNumberRequest createAddMerchantOrderNumberRequest() {
        return new AddMerchantOrderNumberRequest();
    }

    /**
     * Create an instance of {@link CarrierCalculatedShippingOption }
     * 
     */
    public CarrierCalculatedShippingOption createCarrierCalculatedShippingOption() {
        return new CarrierCalculatedShippingOption();
    }

    /**
     * Create an instance of {@link Money }
     * 
     */
    public Money createMoney() {
        return new Money();
    }

    /**
     * Create an instance of {@link GiftMessage }
     * 
     */
    public GiftMessage createGiftMessage() {
        return new GiftMessage();
    }

    /**
     * Create an instance of {@link CarrierCalculatedShippingAdjustment }
     * 
     */
    public CarrierCalculatedShippingAdjustment createCarrierCalculatedShippingAdjustment() {
        return new CarrierCalculatedShippingAdjustment();
    }

    /**
     * Create an instance of {@link ShoppingCart.Items }
     * 
     */
    public ShoppingCart.Items createShoppingCartItems() {
        return new ShoppingCart.Items();
    }

    /**
     * Create an instance of {@link NotificationHistoryResponse.InvalidOrderNumbers }
     * 
     */
    public NotificationHistoryResponse.InvalidOrderNumbers createNotificationHistoryResponseInvalidOrderNumbers() {
        return new NotificationHistoryResponse.InvalidOrderNumbers();
    }

    /**
     * Create an instance of {@link Bye }
     * 
     */
    public Bye createBye() {
        return new Bye();
    }

    /**
     * Create an instance of {@link Calculate.Shipping }
     * 
     */
    public Calculate.Shipping createCalculateShipping() {
        return new Calculate.Shipping();
    }

    /**
     * Create an instance of {@link DiagnoseResponse.Warnings }
     * 
     */
    public DiagnoseResponse.Warnings createDiagnoseResponseWarnings() {
        return new DiagnoseResponse.Warnings();
    }

    /**
     * Create an instance of {@link ReturnItemsRequest.ItemIds }
     * 
     */
    public ReturnItemsRequest.ItemIds createReturnItemsRequestItemIds() {
        return new ReturnItemsRequest.ItemIds();
    }

    /**
     * Create an instance of {@link Pickup }
     * 
     */
    public Pickup createPickup() {
        return new Pickup();
    }

    /**
     * Create an instance of {@link OrderStateChangeNotification }
     * 
     */
    public OrderStateChangeNotification createOrderStateChangeNotification() {
        return new OrderStateChangeNotification();
    }

    /**
     * Create an instance of {@link ResetItemsShippingInformationRequest }
     * 
     */
    public ResetItemsShippingInformationRequest createResetItemsShippingInformationRequest() {
        return new ResetItemsShippingInformationRequest();
    }

    /**
     * Create an instance of {@link BackorderItemsRequest }
     * 
     */
    public BackorderItemsRequest createBackorderItemsRequest() {
        return new BackorderItemsRequest();
    }

    /**
     * Create an instance of {@link StructuredName }
     * 
     */
    public StructuredName createStructuredName() {
        return new StructuredName();
    }

    /**
     * Create an instance of {@link MerchantCalculationResults.Results }
     * 
     */
    public MerchantCalculationResults.Results createMerchantCalculationResultsResults() {
        return new MerchantCalculationResults.Results();
    }

    /**
     * Create an instance of {@link DemographicData }
     * 
     */
    public DemographicData createDemographicData() {
        return new DemographicData();
    }

    /**
     * Create an instance of {@link CarrierCalculatedShipping }
     * 
     */
    public CarrierCalculatedShipping createCarrierCalculatedShipping() {
        return new CarrierCalculatedShipping();
    }

    /**
     * Create an instance of {@link CarrierCalculatedShippingOption.Price }
     * 
     */
    public CarrierCalculatedShippingOption.Price createCarrierCalculatedShippingOptionPrice() {
        return new CarrierCalculatedShippingOption.Price();
    }

    /**
     * Create an instance of {@link CouponResult }
     * 
     */
    public CouponResult createCouponResult() {
        return new CouponResult();
    }

    /**
     * Create an instance of {@link MerchantCalculatedShippingAdjustment }
     * 
     */
    public MerchantCalculatedShippingAdjustment createMerchantCalculatedShippingAdjustment() {
        return new MerchantCalculatedShippingAdjustment();
    }

    /**
     * Create an instance of {@link PickupShippingAdjustment.ShippingCost }
     * 
     */
    public PickupShippingAdjustment.ShippingCost createPickupShippingAdjustmentShippingCost() {
        return new PickupShippingAdjustment.ShippingCost();
    }

    /**
     * Create an instance of {@link ShipItemsRequest }
     * 
     */
    public ShipItemsRequest createShipItemsRequest() {
        return new ShipItemsRequest();
    }

    /**
     * Create an instance of {@link AuthorizeOrderRequest }
     * 
     */
    public AuthorizeOrderRequest createAuthorizeOrderRequest() {
        return new AuthorizeOrderRequest();
    }

    /**
     * Create an instance of {@link WorldArea }
     * 
     */
    public WorldArea createWorldArea() {
        return new WorldArea();
    }

    /**
     * Create an instance of {@link CartExpiration }
     * 
     */
    public CartExpiration createCartExpiration() {
        return new CartExpiration();
    }

    /**
     * Create an instance of {@link DefaultTaxRule.TaxAreas }
     * 
     */
    public DefaultTaxRule.TaxAreas createDefaultTaxRuleTaxAreas() {
        return new DefaultTaxRule.TaxAreas();
    }

    /**
     * Create an instance of {@link CancelItemsRequest }
     * 
     */
    public CancelItemsRequest createCancelItemsRequest() {
        return new CancelItemsRequest();
    }

    /**
     * Create an instance of {@link DefaultTaxTable }
     * 
     */
    public DefaultTaxTable createDefaultTaxTable() {
        return new DefaultTaxTable();
    }

    /**
     * Create an instance of {@link AuthorizationAmountNotification }
     * 
     */
    public AuthorizationAmountNotification createAuthorizationAmountNotification() {
        return new AuthorizationAmountNotification();
    }

    /**
     * Create an instance of {@link MerchantCalculationResults }
     * 
     */
    public MerchantCalculationResults createMerchantCalculationResults() {
        return new MerchantCalculationResults();
    }

    /**
     * Create an instance of {@link BuyerNote }
     * 
     */
    public BuyerNote createBuyerNote() {
        return new BuyerNote();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveOrderRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "archive-order")
    public JAXBElement<ArchiveOrderRequest> createArchiveOrder(ArchiveOrderRequest value) {
        return new JAXBElement<ArchiveOrderRequest>(_ArchiveOrder_QNAME, ArchiveOrderRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddTrackingDataRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "add-tracking-data")
    public JAXBElement<AddTrackingDataRequest> createAddTrackingData(AddTrackingDataRequest value) {
        return new JAXBElement<AddTrackingDataRequest>(_AddTrackingData_QNAME, AddTrackingDataRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DiagnoseResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "diagnosis")
    public JAXBElement<DiagnoseResponse> createDiagnosis(DiagnoseResponse value) {
        return new JAXBElement<DiagnoseResponse>(_Diagnosis_QNAME, DiagnoseResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChargebackAmountNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "chargeback-amount-notification")
    public JAXBElement<ChargebackAmountNotification> createChargebackAmountNotification(ChargebackAmountNotification value) {
        return new JAXBElement<ChargebackAmountNotification>(_ChargebackAmountNotification_QNAME, ChargebackAmountNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderSummaryRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "order-summary-request")
    public JAXBElement<OrderSummaryRequest> createOrderSummaryRequest(OrderSummaryRequest value) {
        return new JAXBElement<OrderSummaryRequest>(_OrderSummaryRequest_QNAME, OrderSummaryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderSummaryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "order-summary-response")
    public JAXBElement<OrderSummaryResponse> createOrderSummaryResponse(OrderSummaryResponse value) {
        return new JAXBElement<OrderSummaryResponse>(_OrderSummaryResponse_QNAME, OrderSummaryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckoutShoppingCart }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "checkout-shopping-cart")
    public JAXBElement<CheckoutShoppingCart> createCheckoutShoppingCart(CheckoutShoppingCart value) {
        return new JAXBElement<CheckoutShoppingCart>(_CheckoutShoppingCart_QNAME, CheckoutShoppingCart.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderStateChangeNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "order-state-change-notification")
    public JAXBElement<OrderStateChangeNotification> createOrderStateChangeNotification(OrderStateChangeNotification value) {
        return new JAXBElement<OrderStateChangeNotification>(_OrderStateChangeNotification_QNAME, OrderStateChangeNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChargeAndShipOrderRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "charge-and-ship-order")
    public JAXBElement<ChargeAndShipOrderRequest> createChargeAndShipOrder(ChargeAndShipOrderRequest value) {
        return new JAXBElement<ChargeAndShipOrderRequest>(_ChargeAndShipOrder_QNAME, ChargeAndShipOrderRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuyerMarketingPreferences }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "buyer-marketing-preferences")
    public JAXBElement<BuyerMarketingPreferences> createBuyerMarketingPreferences(BuyerMarketingPreferences value) {
        return new JAXBElement<BuyerMarketingPreferences>(_BuyerMarketingPreferences_QNAME, BuyerMarketingPreferences.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckoutRedirect }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "checkout-redirect")
    public JAXBElement<CheckoutRedirect> createCheckoutRedirect(CheckoutRedirect value) {
        return new JAXBElement<CheckoutRedirect>(_CheckoutRedirect_QNAME, CheckoutRedirect.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RiskInformationNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "risk-information-notification")
    public JAXBElement<RiskInformationNotification> createRiskInformationNotification(RiskInformationNotification value) {
        return new JAXBElement<RiskInformationNotification>(_RiskInformationNotification_QNAME, RiskInformationNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelItemsRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "cancel-items")
    public JAXBElement<CancelItemsRequest> createCancelItems(CancelItemsRequest value) {
        return new JAXBElement<CancelItemsRequest>(_CancelItems_QNAME, CancelItemsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BackorderItemsRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "backorder-items")
    public JAXBElement<BackorderItemsRequest> createBackorderItems(BackorderItemsRequest value) {
        return new JAXBElement<BackorderItemsRequest>(_BackorderItems_QNAME, BackorderItemsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessOrderRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "process-order")
    public JAXBElement<ProcessOrderRequest> createProcessOrder(ProcessOrderRequest value) {
        return new JAXBElement<ProcessOrderRequest>(_ProcessOrder_QNAME, ProcessOrderRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnarchiveOrderRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "unarchive-order")
    public JAXBElement<UnarchiveOrderRequest> createUnarchiveOrder(UnarchiveOrderRequest value) {
        return new JAXBElement<UnarchiveOrderRequest>(_UnarchiveOrder_QNAME, UnarchiveOrderRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnItemsRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "return-items")
    public JAXBElement<ReturnItemsRequest> createReturnItems(ReturnItemsRequest value) {
        return new JAXBElement<ReturnItemsRequest>(_ReturnItems_QNAME, ReturnItemsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MerchantCalculationCallback }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "merchant-calculation-callback")
    public JAXBElement<MerchantCalculationCallback> createMerchantCalculationCallback(MerchantCalculationCallback value) {
        return new JAXBElement<MerchantCalculationCallback>(_MerchantCalculationCallback_QNAME, MerchantCalculationCallback.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChargeOrderRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "charge-order")
    public JAXBElement<ChargeOrderRequest> createChargeOrder(ChargeOrderRequest value) {
        return new JAXBElement<ChargeOrderRequest>(_ChargeOrder_QNAME, ChargeOrderRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Bye }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "bye")
    public JAXBElement<Bye> createBye(Bye value) {
        return new JAXBElement<Bye>(_Bye_QNAME, Bye.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelOrderRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "cancel-order")
    public JAXBElement<CancelOrderRequest> createCancelOrder(CancelOrderRequest value) {
        return new JAXBElement<CancelOrderRequest>(_CancelOrder_QNAME, CancelOrderRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChargeAmountNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "charge-amount-notification")
    public JAXBElement<ChargeAmountNotification> createChargeAmountNotification(ChargeAmountNotification value) {
        return new JAXBElement<ChargeAmountNotification>(_ChargeAmountNotification_QNAME, ChargeAmountNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefundOrderRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "refund-order")
    public JAXBElement<RefundOrderRequest> createRefundOrder(RefundOrderRequest value) {
        return new JAXBElement<RefundOrderRequest>(_RefundOrder_QNAME, RefundOrderRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MerchantCalculationResults }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "merchant-calculation-results")
    public JAXBElement<MerchantCalculationResults> createMerchantCalculationResults(MerchantCalculationResults value) {
        return new JAXBElement<MerchantCalculationResults>(_MerchantCalculationResults_QNAME, MerchantCalculationResults.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NewOrderNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "new-order-notification")
    public JAXBElement<NewOrderNotification> createNewOrderNotification(NewOrderNotification value) {
        return new JAXBElement<NewOrderNotification>(_NewOrderNotification_QNAME, NewOrderNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "error")
    public JAXBElement<ErrorResponse> createError(ErrorResponse value) {
        return new JAXBElement<ErrorResponse>(_Error_QNAME, ErrorResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetItemsShippingInformationRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "reset-items-shipping-information")
    public JAXBElement<ResetItemsShippingInformationRequest> createResetItemsShippingInformation(ResetItemsShippingInformationRequest value) {
        return new JAXBElement<ResetItemsShippingInformationRequest>(_ResetItemsShippingInformation_QNAME, ResetItemsShippingInformationRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendBuyerMessageRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "send-buyer-message")
    public JAXBElement<SendBuyerMessageRequest> createSendBuyerMessage(SendBuyerMessageRequest value) {
        return new JAXBElement<SendBuyerMessageRequest>(_SendBuyerMessage_QNAME, SendBuyerMessageRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizeOrderRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "authorize-order")
    public JAXBElement<AuthorizeOrderRequest> createAuthorizeOrder(AuthorizeOrderRequest value) {
        return new JAXBElement<AuthorizeOrderRequest>(_AuthorizeOrder_QNAME, AuthorizeOrderRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotificationAcknowledgment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "notification-acknowledgment")
    public JAXBElement<NotificationAcknowledgment> createNotificationAcknowledgment(NotificationAcknowledgment value) {
        return new JAXBElement<NotificationAcknowledgment>(_NotificationAcknowledgment_QNAME, NotificationAcknowledgment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationAmountNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "authorization-amount-notification")
    public JAXBElement<AuthorizationAmountNotification> createAuthorizationAmountNotification(AuthorizationAmountNotification value) {
        return new JAXBElement<AuthorizationAmountNotification>(_AuthorizationAmountNotification_QNAME, AuthorizationAmountNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "order-summary")
    public JAXBElement<OrderSummary> createOrderSummary(OrderSummary value) {
        return new JAXBElement<OrderSummary>(_OrderSummary_QNAME, OrderSummary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShipItemsRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "ship-items")
    public JAXBElement<ShipItemsRequest> createShipItems(ShipItemsRequest value) {
        return new JAXBElement<ShipItemsRequest>(_ShipItems_QNAME, ShipItemsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotificationHistoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "notification-history-response")
    public JAXBElement<NotificationHistoryResponse> createNotificationHistoryResponse(NotificationHistoryResponse value) {
        return new JAXBElement<NotificationHistoryResponse>(_NotificationHistoryResponse_QNAME, NotificationHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefundAmountNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "refund-amount-notification")
    public JAXBElement<RefundAmountNotification> createRefundAmountNotification(RefundAmountNotification value) {
        return new JAXBElement<RefundAmountNotification>(_RefundAmountNotification_QNAME, RefundAmountNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Hello }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "hello")
    public JAXBElement<Hello> createHello(Hello value) {
        return new JAXBElement<Hello>(_Hello_QNAME, Hello.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotificationHistoryRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "notification-history-request")
    public JAXBElement<NotificationHistoryRequest> createNotificationHistoryRequest(NotificationHistoryRequest value) {
        return new JAXBElement<NotificationHistoryRequest>(_NotificationHistoryRequest_QNAME, NotificationHistoryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderListRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "order-list-request")
    public JAXBElement<OrderListRequest> createOrderListRequest(OrderListRequest value) {
        return new JAXBElement<OrderListRequest>(_OrderListRequest_QNAME, OrderListRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeliverOrderRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "deliver-order")
    public JAXBElement<DeliverOrderRequest> createDeliverOrder(DeliverOrderRequest value) {
        return new JAXBElement<DeliverOrderRequest>(_DeliverOrder_QNAME, DeliverOrderRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddMerchantOrderNumberRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "add-merchant-order-number")
    public JAXBElement<AddMerchantOrderNumberRequest> createAddMerchantOrderNumber(AddMerchantOrderNumberRequest value) {
        return new JAXBElement<AddMerchantOrderNumberRequest>(_AddMerchantOrderNumber_QNAME, AddMerchantOrderNumberRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DemoFailure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "demo-failure")
    public JAXBElement<DemoFailure> createDemoFailure(DemoFailure value) {
        return new JAXBElement<DemoFailure>(_DemoFailure_QNAME, DemoFailure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestReceivedResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checkout.google.com/schema/2", name = "request-received")
    public JAXBElement<RequestReceivedResponse> createRequestReceived(RequestReceivedResponse value) {
        return new JAXBElement<RequestReceivedResponse>(_RequestReceived_QNAME, RequestReceivedResponse.class, null, value);
    }

}
