//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.28 at 11:58:56 AM PDT 
//


package com.google.checkout.sdk.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderAdjustment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderAdjustment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="merchant-calculation-successful" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="merchant-codes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="gift-certificate-adjustment" type="{http://checkout.google.com/schema/2}GiftCertificateAdjustment"/>
 *                     &lt;element name="coupon-adjustment" type="{http://checkout.google.com/schema/2}CouponAdjustment"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="total-tax" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;restriction base="&lt;http://checkout.google.com/schema/2>Money">
 *               &lt;/restriction>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="shipping" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="merchant-calculated-shipping-adjustment" type="{http://checkout.google.com/schema/2}MerchantCalculatedShippingAdjustment"/>
 *                   &lt;element name="flat-rate-shipping-adjustment" type="{http://checkout.google.com/schema/2}FlatRateShippingAdjustment"/>
 *                   &lt;element name="pickup-shipping-adjustment" type="{http://checkout.google.com/schema/2}PickupShippingAdjustment"/>
 *                   &lt;element name="carrier-calculated-shipping-adjustment" type="{http://checkout.google.com/schema/2}CarrierCalculatedShippingAdjustment"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="adjustment-total" type="{http://checkout.google.com/schema/2}Money" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderAdjustment", namespace = "http://checkout.google.com/schema/2", propOrder = {

})
public class OrderAdjustment {

    @XmlElement(name = "merchant-calculation-successful", namespace = "http://checkout.google.com/schema/2")
    protected Boolean merchantCalculationSuccessful;
    @XmlElement(name = "merchant-codes", namespace = "http://checkout.google.com/schema/2")
    protected OrderAdjustment.MerchantCodes merchantCodes;
    @XmlElement(name = "total-tax", namespace = "http://checkout.google.com/schema/2")
    protected OrderAdjustment.TotalTax totalTax;
    @XmlElement(namespace = "http://checkout.google.com/schema/2")
    protected OrderAdjustment.Shipping shipping;
    @XmlElement(name = "adjustment-total", namespace = "http://checkout.google.com/schema/2")
    protected Money adjustmentTotal;

    /**
     * Gets the value of the merchantCalculationSuccessful property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMerchantCalculationSuccessful() {
        return merchantCalculationSuccessful;
    }

    /**
     * Sets the value of the merchantCalculationSuccessful property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMerchantCalculationSuccessful(Boolean value) {
        this.merchantCalculationSuccessful = value;
    }

    /**
     * Gets the value of the merchantCodes property.
     * 
     * @return
     *     possible object is
     *     {@link OrderAdjustment.MerchantCodes }
     *     
     */
    public OrderAdjustment.MerchantCodes getMerchantCodes() {
        return merchantCodes;
    }

    /**
     * Sets the value of the merchantCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderAdjustment.MerchantCodes }
     *     
     */
    public void setMerchantCodes(OrderAdjustment.MerchantCodes value) {
        this.merchantCodes = value;
    }

    /**
     * Gets the value of the totalTax property.
     * 
     * @return
     *     possible object is
     *     {@link OrderAdjustment.TotalTax }
     *     
     */
    public OrderAdjustment.TotalTax getTotalTax() {
        return totalTax;
    }

    /**
     * Sets the value of the totalTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderAdjustment.TotalTax }
     *     
     */
    public void setTotalTax(OrderAdjustment.TotalTax value) {
        this.totalTax = value;
    }

    /**
     * Gets the value of the shipping property.
     * 
     * @return
     *     possible object is
     *     {@link OrderAdjustment.Shipping }
     *     
     */
    public OrderAdjustment.Shipping getShipping() {
        return shipping;
    }

    /**
     * Sets the value of the shipping property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderAdjustment.Shipping }
     *     
     */
    public void setShipping(OrderAdjustment.Shipping value) {
        this.shipping = value;
    }

    /**
     * Gets the value of the adjustmentTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getAdjustmentTotal() {
        return adjustmentTotal;
    }

    /**
     * Sets the value of the adjustmentTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setAdjustmentTotal(Money value) {
        this.adjustmentTotal = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="gift-certificate-adjustment" type="{http://checkout.google.com/schema/2}GiftCertificateAdjustment"/>
     *           &lt;element name="coupon-adjustment" type="{http://checkout.google.com/schema/2}CouponAdjustment"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "giftCertificateAdjustmentOrCouponAdjustment"
    })
    public static class MerchantCodes {

        @XmlElements({
            @XmlElement(name = "gift-certificate-adjustment", namespace = "http://checkout.google.com/schema/2", type = GiftCertificateAdjustment.class),
            @XmlElement(name = "coupon-adjustment", namespace = "http://checkout.google.com/schema/2", type = CouponAdjustment.class)
        })
        protected List<Object> giftCertificateAdjustmentOrCouponAdjustment;

        /**
         * Gets the value of the giftCertificateAdjustmentOrCouponAdjustment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the giftCertificateAdjustmentOrCouponAdjustment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGiftCertificateAdjustmentOrCouponAdjustment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GiftCertificateAdjustment }
         * {@link CouponAdjustment }
         * 
         * 
         */
        public List<Object> getGiftCertificateAdjustmentOrCouponAdjustment() {
            if (giftCertificateAdjustmentOrCouponAdjustment == null) {
                giftCertificateAdjustmentOrCouponAdjustment = new ArrayList<Object>();
            }
            return this.giftCertificateAdjustmentOrCouponAdjustment;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="merchant-calculated-shipping-adjustment" type="{http://checkout.google.com/schema/2}MerchantCalculatedShippingAdjustment"/>
     *         &lt;element name="flat-rate-shipping-adjustment" type="{http://checkout.google.com/schema/2}FlatRateShippingAdjustment"/>
     *         &lt;element name="pickup-shipping-adjustment" type="{http://checkout.google.com/schema/2}PickupShippingAdjustment"/>
     *         &lt;element name="carrier-calculated-shipping-adjustment" type="{http://checkout.google.com/schema/2}CarrierCalculatedShippingAdjustment"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "merchantCalculatedShippingAdjustment",
        "flatRateShippingAdjustment",
        "pickupShippingAdjustment",
        "carrierCalculatedShippingAdjustment"
    })
    public static class Shipping {

        @XmlElement(name = "merchant-calculated-shipping-adjustment", namespace = "http://checkout.google.com/schema/2")
        protected MerchantCalculatedShippingAdjustment merchantCalculatedShippingAdjustment;
        @XmlElement(name = "flat-rate-shipping-adjustment", namespace = "http://checkout.google.com/schema/2")
        protected FlatRateShippingAdjustment flatRateShippingAdjustment;
        @XmlElement(name = "pickup-shipping-adjustment", namespace = "http://checkout.google.com/schema/2")
        protected PickupShippingAdjustment pickupShippingAdjustment;
        @XmlElement(name = "carrier-calculated-shipping-adjustment", namespace = "http://checkout.google.com/schema/2")
        protected CarrierCalculatedShippingAdjustment carrierCalculatedShippingAdjustment;

        /**
         * Gets the value of the merchantCalculatedShippingAdjustment property.
         * 
         * @return
         *     possible object is
         *     {@link MerchantCalculatedShippingAdjustment }
         *     
         */
        public MerchantCalculatedShippingAdjustment getMerchantCalculatedShippingAdjustment() {
            return merchantCalculatedShippingAdjustment;
        }

        /**
         * Sets the value of the merchantCalculatedShippingAdjustment property.
         * 
         * @param value
         *     allowed object is
         *     {@link MerchantCalculatedShippingAdjustment }
         *     
         */
        public void setMerchantCalculatedShippingAdjustment(MerchantCalculatedShippingAdjustment value) {
            this.merchantCalculatedShippingAdjustment = value;
        }

        /**
         * Gets the value of the flatRateShippingAdjustment property.
         * 
         * @return
         *     possible object is
         *     {@link FlatRateShippingAdjustment }
         *     
         */
        public FlatRateShippingAdjustment getFlatRateShippingAdjustment() {
            return flatRateShippingAdjustment;
        }

        /**
         * Sets the value of the flatRateShippingAdjustment property.
         * 
         * @param value
         *     allowed object is
         *     {@link FlatRateShippingAdjustment }
         *     
         */
        public void setFlatRateShippingAdjustment(FlatRateShippingAdjustment value) {
            this.flatRateShippingAdjustment = value;
        }

        /**
         * Gets the value of the pickupShippingAdjustment property.
         * 
         * @return
         *     possible object is
         *     {@link PickupShippingAdjustment }
         *     
         */
        public PickupShippingAdjustment getPickupShippingAdjustment() {
            return pickupShippingAdjustment;
        }

        /**
         * Sets the value of the pickupShippingAdjustment property.
         * 
         * @param value
         *     allowed object is
         *     {@link PickupShippingAdjustment }
         *     
         */
        public void setPickupShippingAdjustment(PickupShippingAdjustment value) {
            this.pickupShippingAdjustment = value;
        }

        /**
         * Gets the value of the carrierCalculatedShippingAdjustment property.
         * 
         * @return
         *     possible object is
         *     {@link CarrierCalculatedShippingAdjustment }
         *     
         */
        public CarrierCalculatedShippingAdjustment getCarrierCalculatedShippingAdjustment() {
            return carrierCalculatedShippingAdjustment;
        }

        /**
         * Sets the value of the carrierCalculatedShippingAdjustment property.
         * 
         * @param value
         *     allowed object is
         *     {@link CarrierCalculatedShippingAdjustment }
         *     
         */
        public void setCarrierCalculatedShippingAdjustment(CarrierCalculatedShippingAdjustment value) {
            this.carrierCalculatedShippingAdjustment = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;restriction base="&lt;http://checkout.google.com/schema/2>Money">
     *     &lt;/restriction>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class TotalTax
        extends Money
    {


    }

}
