//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.23 at 12:14:48 PM PDT 
//


package com.google.checkout.sdk.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for USCountryArea complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="USCountryArea">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="country-area" use="required" type="{http://checkout.google.com/schema/2}USAreas" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "USCountryArea", namespace = "http://checkout.google.com/schema/2")
public class USCountryArea {

    @XmlAttribute(name = "country-area", required = true)
    protected USAreas countryArea;

    /**
     * Gets the value of the countryArea property.
     * 
     * @return
     *     possible object is
     *     {@link USAreas }
     *     
     */
    public USAreas getCountryArea() {
        return countryArea;
    }

    /**
     * Sets the value of the countryArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link USAreas }
     *     
     */
    public void setCountryArea(USAreas value) {
        this.countryArea = value;
    }

}
