//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.28 at 11:58:56 AM PDT 
//


package com.google.checkout.sdk.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FlatRateShipping complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlatRateShipping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="price">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;restriction base="&lt;http://checkout.google.com/schema/2>Money">
 *               &lt;/restriction>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="shipping-restrictions" type="{http://checkout.google.com/schema/2}ShippingRestrictions" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="255"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlatRateShipping", namespace = "http://checkout.google.com/schema/2", propOrder = {

})
public class FlatRateShipping {

    @XmlElement(namespace = "http://checkout.google.com/schema/2", required = true)
    protected FlatRateShipping.Price price;
    @XmlElement(name = "shipping-restrictions", namespace = "http://checkout.google.com/schema/2")
    protected ShippingRestrictions shippingRestrictions;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link FlatRateShipping.Price }
     *     
     */
    public FlatRateShipping.Price getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlatRateShipping.Price }
     *     
     */
    public void setPrice(FlatRateShipping.Price value) {
        this.price = value;
    }

    /**
     * Gets the value of the shippingRestrictions property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingRestrictions }
     *     
     */
    public ShippingRestrictions getShippingRestrictions() {
        return shippingRestrictions;
    }

    /**
     * Sets the value of the shippingRestrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingRestrictions }
     *     
     */
    public void setShippingRestrictions(ShippingRestrictions value) {
        this.shippingRestrictions = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;restriction base="&lt;http://checkout.google.com/schema/2>Money">
     *     &lt;/restriction>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Price
        extends Money
    {


    }

}
