#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -cp "$APPDIR/src:$APPDIR/bin:/Applications/gwt-1.4.60/gwt-user.jar:/Applications/gwt-1.4.60/gwt-dev-mac.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" com.google.checkout.samples.store.Store;
