//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.28 at 11:58:56 AM PDT 
//


package com.google.checkout.sdk.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MerchantCalculations complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MerchantCalculations">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="merchant-calculations-url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="accept-merchant-coupons" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="accept-gift-certificates" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MerchantCalculations", namespace = "http://checkout.google.com/schema/2", propOrder = {

})
public class MerchantCalculations {

    @XmlElement(name = "merchant-calculations-url", namespace = "http://checkout.google.com/schema/2", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String merchantCalculationsUrl;
    @XmlElement(name = "accept-merchant-coupons", namespace = "http://checkout.google.com/schema/2")
    protected Boolean acceptMerchantCoupons;
    @XmlElement(name = "accept-gift-certificates", namespace = "http://checkout.google.com/schema/2")
    protected Boolean acceptGiftCertificates;

    /**
     * Gets the value of the merchantCalculationsUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantCalculationsUrl() {
        return merchantCalculationsUrl;
    }

    /**
     * Sets the value of the merchantCalculationsUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantCalculationsUrl(String value) {
        this.merchantCalculationsUrl = value;
    }

    /**
     * Gets the value of the acceptMerchantCoupons property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAcceptMerchantCoupons() {
        return acceptMerchantCoupons;
    }

    /**
     * Sets the value of the acceptMerchantCoupons property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAcceptMerchantCoupons(Boolean value) {
        this.acceptMerchantCoupons = value;
    }

    /**
     * Gets the value of the acceptGiftCertificates property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAcceptGiftCertificates() {
        return acceptGiftCertificates;
    }

    /**
     * Sets the value of the acceptGiftCertificates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAcceptGiftCertificates(Boolean value) {
        this.acceptGiftCertificates = value;
    }

}
