//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.28 at 11:58:56 AM PDT 
//


package com.google.checkout.sdk.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OrderSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="google-order-number" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="merchant-order-number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="total-refund-amount" type="{http://checkout.google.com/schema/2}Money"/>
 *         &lt;element name="total-charge-amount" type="{http://checkout.google.com/schema/2}Money"/>
 *         &lt;element name="authorization" type="{http://checkout.google.com/schema/2}AuthorizationInformation" minOccurs="0"/>
 *         &lt;element name="risk-information" type="{http://checkout.google.com/schema/2}RiskInformation" minOccurs="0"/>
 *         &lt;element name="total-chargeback-amount" type="{http://checkout.google.com/schema/2}Money"/>
 *         &lt;element name="purchase-date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="archived" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="shopping-cart" type="{http://checkout.google.com/schema/2}ShoppingCart"/>
 *         &lt;element name="order-adjustment" type="{http://checkout.google.com/schema/2}OrderAdjustment"/>
 *         &lt;element name="buyer-shipping-address" type="{http://checkout.google.com/schema/2}Address"/>
 *         &lt;element name="buyer-marketing-preferences" type="{http://checkout.google.com/schema/2}BuyerMarketingPreferences"/>
 *         &lt;element name="promotions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="promotion" type="{http://checkout.google.com/schema/2}Promotion" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="order-total" type="{http://checkout.google.com/schema/2}Money"/>
 *         &lt;element name="fulfillment-order-state" type="{http://checkout.google.com/schema/2}FulfillmentOrderState"/>
 *         &lt;element name="financial-order-state" type="{http://checkout.google.com/schema/2}FinancialOrderState"/>
 *         &lt;element name="buyer-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderSummary", namespace = "http://checkout.google.com/schema/2", propOrder = {

})
public class OrderSummary {

    @XmlElement(name = "google-order-number", namespace = "http://checkout.google.com/schema/2", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String googleOrderNumber;
    @XmlElement(name = "merchant-order-number", namespace = "http://checkout.google.com/schema/2")
    protected String merchantOrderNumber;
    @XmlElement(name = "total-refund-amount", namespace = "http://checkout.google.com/schema/2", required = true)
    protected Money totalRefundAmount;
    @XmlElement(name = "total-charge-amount", namespace = "http://checkout.google.com/schema/2", required = true)
    protected Money totalChargeAmount;
    @XmlElement(namespace = "http://checkout.google.com/schema/2")
    protected AuthorizationInformation authorization;
    @XmlElement(name = "risk-information", namespace = "http://checkout.google.com/schema/2")
    protected RiskInformation riskInformation;
    @XmlElement(name = "total-chargeback-amount", namespace = "http://checkout.google.com/schema/2", required = true)
    protected Money totalChargebackAmount;
    @XmlElement(name = "purchase-date", namespace = "http://checkout.google.com/schema/2", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar purchaseDate;
    @XmlElement(namespace = "http://checkout.google.com/schema/2")
    protected boolean archived;
    @XmlElement(name = "shopping-cart", namespace = "http://checkout.google.com/schema/2", required = true)
    protected ShoppingCart shoppingCart;
    @XmlElement(name = "order-adjustment", namespace = "http://checkout.google.com/schema/2", required = true)
    protected OrderAdjustment orderAdjustment;
    @XmlElement(name = "buyer-shipping-address", namespace = "http://checkout.google.com/schema/2", required = true)
    protected Address buyerShippingAddress;
    @XmlElement(name = "buyer-marketing-preferences", namespace = "http://checkout.google.com/schema/2", required = true)
    protected BuyerMarketingPreferences buyerMarketingPreferences;
    @XmlElement(namespace = "http://checkout.google.com/schema/2")
    protected OrderSummary.Promotions promotions;
    @XmlElement(name = "order-total", namespace = "http://checkout.google.com/schema/2", required = true)
    protected Money orderTotal;
    @XmlElement(name = "fulfillment-order-state", namespace = "http://checkout.google.com/schema/2", required = true)
    protected FulfillmentOrderState fulfillmentOrderState;
    @XmlElement(name = "financial-order-state", namespace = "http://checkout.google.com/schema/2", required = true)
    protected FinancialOrderState financialOrderState;
    @XmlElement(name = "buyer-id", namespace = "http://checkout.google.com/schema/2")
    protected long buyerId;

    /**
     * Gets the value of the googleOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoogleOrderNumber() {
        return googleOrderNumber;
    }

    /**
     * Sets the value of the googleOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoogleOrderNumber(String value) {
        this.googleOrderNumber = value;
    }

    /**
     * Gets the value of the merchantOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantOrderNumber() {
        return merchantOrderNumber;
    }

    /**
     * Sets the value of the merchantOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantOrderNumber(String value) {
        this.merchantOrderNumber = value;
    }

    /**
     * Gets the value of the totalRefundAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getTotalRefundAmount() {
        return totalRefundAmount;
    }

    /**
     * Sets the value of the totalRefundAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setTotalRefundAmount(Money value) {
        this.totalRefundAmount = value;
    }

    /**
     * Gets the value of the totalChargeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getTotalChargeAmount() {
        return totalChargeAmount;
    }

    /**
     * Sets the value of the totalChargeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setTotalChargeAmount(Money value) {
        this.totalChargeAmount = value;
    }

    /**
     * Gets the value of the authorization property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorizationInformation }
     *     
     */
    public AuthorizationInformation getAuthorization() {
        return authorization;
    }

    /**
     * Sets the value of the authorization property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorizationInformation }
     *     
     */
    public void setAuthorization(AuthorizationInformation value) {
        this.authorization = value;
    }

    /**
     * Gets the value of the riskInformation property.
     * 
     * @return
     *     possible object is
     *     {@link RiskInformation }
     *     
     */
    public RiskInformation getRiskInformation() {
        return riskInformation;
    }

    /**
     * Sets the value of the riskInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiskInformation }
     *     
     */
    public void setRiskInformation(RiskInformation value) {
        this.riskInformation = value;
    }

    /**
     * Gets the value of the totalChargebackAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getTotalChargebackAmount() {
        return totalChargebackAmount;
    }

    /**
     * Sets the value of the totalChargebackAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setTotalChargebackAmount(Money value) {
        this.totalChargebackAmount = value;
    }

    /**
     * Gets the value of the purchaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * Sets the value of the purchaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPurchaseDate(XMLGregorianCalendar value) {
        this.purchaseDate = value;
    }

    /**
     * Gets the value of the archived property.
     * 
     */
    public boolean isArchived() {
        return archived;
    }

    /**
     * Sets the value of the archived property.
     * 
     */
    public void setArchived(boolean value) {
        this.archived = value;
    }

    /**
     * Gets the value of the shoppingCart property.
     * 
     * @return
     *     possible object is
     *     {@link ShoppingCart }
     *     
     */
    public ShoppingCart getShoppingCart() {
        return shoppingCart;
    }

    /**
     * Sets the value of the shoppingCart property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShoppingCart }
     *     
     */
    public void setShoppingCart(ShoppingCart value) {
        this.shoppingCart = value;
    }

    /**
     * Gets the value of the orderAdjustment property.
     * 
     * @return
     *     possible object is
     *     {@link OrderAdjustment }
     *     
     */
    public OrderAdjustment getOrderAdjustment() {
        return orderAdjustment;
    }

    /**
     * Sets the value of the orderAdjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderAdjustment }
     *     
     */
    public void setOrderAdjustment(OrderAdjustment value) {
        this.orderAdjustment = value;
    }

    /**
     * Gets the value of the buyerShippingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getBuyerShippingAddress() {
        return buyerShippingAddress;
    }

    /**
     * Sets the value of the buyerShippingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setBuyerShippingAddress(Address value) {
        this.buyerShippingAddress = value;
    }

    /**
     * Gets the value of the buyerMarketingPreferences property.
     * 
     * @return
     *     possible object is
     *     {@link BuyerMarketingPreferences }
     *     
     */
    public BuyerMarketingPreferences getBuyerMarketingPreferences() {
        return buyerMarketingPreferences;
    }

    /**
     * Sets the value of the buyerMarketingPreferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyerMarketingPreferences }
     *     
     */
    public void setBuyerMarketingPreferences(BuyerMarketingPreferences value) {
        this.buyerMarketingPreferences = value;
    }

    /**
     * Gets the value of the promotions property.
     * 
     * @return
     *     possible object is
     *     {@link OrderSummary.Promotions }
     *     
     */
    public OrderSummary.Promotions getPromotions() {
        return promotions;
    }

    /**
     * Sets the value of the promotions property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderSummary.Promotions }
     *     
     */
    public void setPromotions(OrderSummary.Promotions value) {
        this.promotions = value;
    }

    /**
     * Gets the value of the orderTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getOrderTotal() {
        return orderTotal;
    }

    /**
     * Sets the value of the orderTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setOrderTotal(Money value) {
        this.orderTotal = value;
    }

    /**
     * Gets the value of the fulfillmentOrderState property.
     * 
     * @return
     *     possible object is
     *     {@link FulfillmentOrderState }
     *     
     */
    public FulfillmentOrderState getFulfillmentOrderState() {
        return fulfillmentOrderState;
    }

    /**
     * Sets the value of the fulfillmentOrderState property.
     * 
     * @param value
     *     allowed object is
     *     {@link FulfillmentOrderState }
     *     
     */
    public void setFulfillmentOrderState(FulfillmentOrderState value) {
        this.fulfillmentOrderState = value;
    }

    /**
     * Gets the value of the financialOrderState property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialOrderState }
     *     
     */
    public FinancialOrderState getFinancialOrderState() {
        return financialOrderState;
    }

    /**
     * Sets the value of the financialOrderState property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialOrderState }
     *     
     */
    public void setFinancialOrderState(FinancialOrderState value) {
        this.financialOrderState = value;
    }

    /**
     * Gets the value of the buyerId property.
     * 
     */
    public long getBuyerId() {
        return buyerId;
    }

    /**
     * Sets the value of the buyerId property.
     * 
     */
    public void setBuyerId(long value) {
        this.buyerId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="promotion" type="{http://checkout.google.com/schema/2}Promotion" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "promotion"
    })
    public static class Promotions {

        @XmlElement(namespace = "http://checkout.google.com/schema/2")
        protected List<Promotion> promotion;

        /**
         * Gets the value of the promotion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the promotion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPromotion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Promotion }
         * 
         * 
         */
        public List<Promotion> getPromotion() {
            if (promotion == null) {
                promotion = new ArrayList<Promotion>();
            }
            return this.promotion;
        }

    }


    public javax.xml.bind.JAXBElement<OrderSummary> toJAXB() {
      return com.google.checkout.sdk.util.Utils.objectFactory().createOrderSummary(this);
    }

    @Override
    public String toString() {
      return com.google.checkout.sdk.util.Utils.toXML(toJAXB());
    }
}
