//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.23 at 12:14:48 PM PDT 
//


package com.google.checkout.sdk.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderSummaryResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderSummaryResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="order-summaries">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="order-summary" type="{http://checkout.google.com/schema/2}OrderSummary" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="serial-number" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderSummaryResponse", namespace = "http://checkout.google.com/schema/2", propOrder = {

})
public class OrderSummaryResponse {

    @XmlElement(name = "order-summaries", namespace = "http://checkout.google.com/schema/2", required = true)
    protected OrderSummaryResponse.OrderSummaries orderSummaries;
    @XmlAttribute(name = "serial-number", required = true)
    protected String serialNumber;

    /**
     * Gets the value of the orderSummaries property.
     * 
     * @return
     *     possible object is
     *     {@link OrderSummaryResponse.OrderSummaries }
     *     
     */
    public OrderSummaryResponse.OrderSummaries getOrderSummaries() {
        return orderSummaries;
    }

    /**
     * Sets the value of the orderSummaries property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderSummaryResponse.OrderSummaries }
     *     
     */
    public void setOrderSummaries(OrderSummaryResponse.OrderSummaries value) {
        this.orderSummaries = value;
    }

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="order-summary" type="{http://checkout.google.com/schema/2}OrderSummary" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orderSummary"
    })
    public static class OrderSummaries {

        @XmlElement(name = "order-summary", namespace = "http://checkout.google.com/schema/2")
        protected List<OrderSummary> orderSummary;

        /**
         * Gets the value of the orderSummary property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the orderSummary property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrderSummary().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OrderSummary }
         * 
         * 
         */
        public List<OrderSummary> getOrderSummary() {
            if (orderSummary == null) {
                orderSummary = new ArrayList<OrderSummary>();
            }
            return this.orderSummary;
        }

    }


    public javax.xml.bind.JAXBElement<OrderSummaryResponse> toJAXB() {
      return com.google.checkout.sdk.util.Utils.objectFactory().createOrderSummaryResponse(this);
    }

    @Override
    public String toString() {
      return com.google.checkout.sdk.util.Utils.toXML(toJAXB());
    }
}
